
        version: '3'
        services:
          db:
            image: mysql:5.7
            volumes:
              - db_data:/var/lib/mysql
            restart: always
            environment:
              MYSQL_ROOT_PASSWORD: example_root_password
              MYSQL_DATABASE: blabla.com_db
              MYSQL_USER: blabla.com_user
              MYSQL_PASSWORD: example_password
        
          wordpress:
            depends_on:
              - db
            image: wordpress:latest
            volumes:
              - wp_data:/var/www/html
            ports:
              - "80:80"
            restart: always
            environment:
              WORDPRESS_DB_HOST: db:3306
              WORDPRESS_DB_NAME: blabla.com_db
              WORDPRESS_DB_USER: blabla.com_user
              WORDPRESS_DB_PASSWORD: example_password

        volumes:
          db_data:
          wp_data:
        